# Generated by Django 2.2.5 on 2019-09-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('expiration_date', models.DateField()),
                ('priority', models.CharField(choices=[('H', 'HIGH'), ('R', 'REGULAR'), ('L', 'LOW')], max_length=1)),
            ],
        ),
    ]
